version: "3"

services:
    fronend-static:
        build: .
        restart: always
        ports:
        - "8080:80"
        - "8443:443"
        volumes: 
        - "./certificates:/etc/ssl/certs"
